site_name: Azaka
site_description: Documentation for Azaka. An API Wrapper for VNDB written in Python.
site_author: mooncell07

theme:
  features:
    - navigation.top
  name: material
  logo: img/mask.png
  custom_dir: overrides
  favicon: img/mask.ico
  palette:
    - scheme: slate
      primary: light blue
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
    - scheme: default
      primary: light blue
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode

nav:
  - Home: index.md
  - API-Reference:
    - public:
      - Client: API-Reference/public/client.md
      - Context: API-Reference/public/context.md
      - Paginator: API-Reference/public/paginator.md
      - Interface: API-Reference/public/interface.md
      - Exceptions: API-Reference/public/exceptions.md
      - Enums: API-Reference/public/enums.md
      - Condition: API-Reference/public/condition.md

      - Objects:
        - Character: API-Reference/public/objects/character.md
        - DBStats: API-Reference/public/objects/dbstats.md
        - Producer: API-Reference/public/objects/producer.md
        - Quote: API-Reference/public/objects/quote.md
        - Release: API-Reference/public/objects/release.md
        - Staff: API-Reference/public/objects/staff.md
        - Ulist: API-Reference/public/objects/ulist.md
        - UlistLabels: API-Reference/public/objects/ulistlabels.md
        - User: API-Reference/public/objects/user.md
        - VN: API-Reference/public/objects/vn.md

    - internal:
      - Commands:
        - Command: API-Reference/internals/commands/command.md
      - Tools:
        - Mixins: API-Reference/internals/tools/mixins.md

plugins:
- search
- mkdocstrings:
    handlers:
      python:
        rendering:
            show_source: false
            show_root_heading: true
            members_order: "source"
        import:
          - https://docs.python.org/3.10/objects.inv

repo_name: mooncell07/Azaka
repo_url: https://github.com/mooncell07/Azaka

extra_css:
- ./css/margin.css
- ./css/extra.css
copyright: Copyright 2021 - Present &copy; mooncell07

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - admonition
  - toc:
      permalink: "+"
