site_name: Azaka
site_description: Documentation for Azaka. An API Wrapper for VNDB written in Python.
site_author: mooncell07

theme:
  features:
    - navigation.top
  name: material
  logo: img/mask.png
  favicon: img/mask.ico
  palette:
    - scheme: slate
      primary: light blue
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
    - scheme: default
      primary: light blue
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode

nav:
  - Home: index.md
  - API-Reference:
    - Client: API-Reference/client.md
    - Context: API-Reference/context.md
    - Objects:
      - Character: API-Reference/objects/character.md

plugins:
- search
- mkdocstrings:
    handlers:
      python:
        rendering:
            show_source: false
            show_root_heading: true
            members_order: "source"
        import:
          - https://docs.python.org/3.10/objects.inv

repo_name: mooncell07/Azaka
repo_url: https://github.com/mooncell07/Azaka

extra_css:
- ./css/margin.css
- ./css/extra.css
copyright: Copyright 2021 - Present &copy; mooncell07

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - admonition
  - toc:
      permalink: "+"
