STATUS_INVALID_REQUEST_BODY = 400
STATUS_INVALID_AUTH_TOKEN = 401
STATUS_NOT_FOUND = 404
STATUS_THROTTLED = 429
STATUS_SERVER_ERROR = 500
STATUS_SERVER_DOWN = 502


class AzakaException(Exception):
    """
    Base Exception for Azaka.

    Attributes:
        msg str: The error message generated by the API.
        status_code int: The status code of the error.
    """
    __slots__ = ("msg", "status_code")

    def __init__(self, msg: str, status_code: int) -> None:
        self.msg = msg
        self.status_code = status_code
        super().__init__(msg)


class InvalidRequestBodyError(AzakaException):
    """
    Raised when the request body is invalid. API generates the error message which indicates
    the issue with the request body.

    Status code: `400`
    """
    def __init__(self, msg: str) -> None:
        super().__init__(msg, STATUS_INVALID_REQUEST_BODY)


class InvalidAuthTokenError(AzakaException):
    """
    Raised when the Authentication Token is invalid.

    Status code: `401`
    """
    def __init__(self, msg: str) -> None:
        super().__init__(msg, STATUS_INVALID_AUTH_TOKEN)


class NotFoundError(AzakaException):
    """
    Raised when the API path or HTTP method is invalid.

    Status code: `404`
    """
    def __init__(self, msg: str) -> None:
        super().__init__(msg, STATUS_NOT_FOUND)


class ThrottledError(AzakaException):
    """
    Raised when we are getting rate limited by the API.

    Status code: `429`
    """
    def __init__(self, msg: str) -> None:
        super().__init__(msg, STATUS_THROTTLED)


class ServerError(AzakaException):
    """
    Raised when the server encounters an error.

    Status code: `500`
    """
    def __init__(self, msg: str) -> None:
        super().__init__(msg, STATUS_SERVER_ERROR)


class ServerDownError(AzakaException):
    """
    Raised when the server is down.

    Status code: `502`
    """
    def __init__(self, msg: str) -> None:
        super().__init__(msg, STATUS_SERVER_DOWN)


EXMAP = {
    STATUS_INVALID_REQUEST_BODY: InvalidRequestBodyError,
    STATUS_INVALID_AUTH_TOKEN: InvalidAuthTokenError,
    STATUS_NOT_FOUND: NotFoundError,
    STATUS_THROTTLED: ThrottledError,
    STATUS_SERVER_ERROR: ServerError,
    STATUS_SERVER_DOWN: ServerDownError,
}
